"""create initial four tables

Revision ID: 15a61de1c13e
Revises: 
Create Date: 2026-08-31 18:19:16.943926

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '15a61de1c13e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # 以下に自動生成されたop.create_tableが続く
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name=op.f('ck_users_role_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('encoding', sa.String(length=50), server_default='UTF-8', nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='uploaded', nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'uploaded',\n                'validating',\n                'processing',\n                'completed',\n                'failed'\n            )\n            ", name=op.f('ck_uploaded_files_status_allowed')),
    sa.CheckConstraint('file_size > 0', name=op.f('ck_uploaded_files_file_size_positive')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_uploaded_files_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_uploaded_files_stored_filename'))
    )
    op.create_index(op.f('ix_uploaded_files_checksum'), 'uploaded_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_uploaded_files_equipment_id'), 'uploaded_files', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_measurement_date'), 'uploaded_files', ['measurement_date'], unique=False)
    op.create_index(op.f('ix_uploaded_files_status'), 'uploaded_files', ['status'], unique=False)
    op.create_index(op.f('ix_uploaded_files_uploaded_at'), 'uploaded_files', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_uploaded_by'), 'uploaded_files', ['uploaded_by'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('minimum_value', sa.Float(), nullable=False),
    sa.Column('maximum_value', sa.Float(), nullable=False),
    sa.Column('average_value', sa.Float(), nullable=False),
    sa.Column('median_value', sa.Float(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('anomaly_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='requires_attention', nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('chart_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('anomaly_count >= 0', name=op.f('ck_reports_anomaly_count_non_negative')),
    sa.CheckConstraint('minimum_value <= maximum_value', name=op.f('ck_reports_minimum_not_greater_than_maximum')),
    sa.CheckConstraint('record_count > 0', name=op.f('ck_reports_record_count_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], name=op.f('fk_reports_uploaded_file_id_uploaded_files'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('uploaded_file_id', name=op.f('uq_reports_uploaded_file_id'))
    )
    op.create_index(op.f('ix_reports_anomaly_count'), 'reports', ['anomaly_count'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_created_by'), 'reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_reports_equipment_id'), 'reports', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_reports_measurement_date'), 'reports', ['measurement_date'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('report_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_type', sa.String(length=50), server_default='full_report', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=True),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_report_chunks_chunk_index_non_negative')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_chunks_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_chunks')),
    sa.UniqueConstraint('report_id', 'chunk_index', name='uq_report_chunks_report_id_chunk_index')
    )
    op.create_index(op.f('ix_report_chunks_chunk_type'), 'report_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_report_chunks_equipment_id'), 'report_chunks', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_report_chunks_measurement_date'), 'report_chunks', ['measurement_date'], unique=False)
    op.create_index(op.f('ix_report_chunks_report_id'), 'report_chunks', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_chunks_report_id'), table_name='report_chunks')
    op.drop_index(op.f('ix_report_chunks_measurement_date'), table_name='report_chunks')
    op.drop_index(op.f('ix_report_chunks_equipment_id'), table_name='report_chunks')
    op.drop_index(op.f('ix_report_chunks_chunk_type'), table_name='report_chunks')
    op.drop_table('report_chunks')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_measurement_date'), table_name='reports')
    op.drop_index(op.f('ix_reports_equipment_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_anomaly_count'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_uploaded_files_uploaded_by'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_uploaded_at'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_status'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_measurement_date'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_equipment_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_checksum'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
